// src/lib/components/ui/Dialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { fade, scale } from "svelte/transition";
  import { cubicOut } from "svelte/easing";

  interface Props {
    open: boolean;
    onClose: () => void;
    children: Snippet;
    title?: Snippet;
    description?: Snippet;
    class?: string;
  }

  let {
    open,
    onClose,
    children,
    title,
    description,
    class: className = "",
  }: Props = $props();

  function onKey(e: KeyboardEvent) {
    if (e.key === "Escape") onClose();
  }
</script>

<svelte:window onkeydown={onKey} />

{#if open}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center p-4"
    role="dialog"
    aria-modal="true"
  >
    <button
      type="button"
      aria-label="Close"
      class="fixed inset-0 bg-black/80 backdrop-blur-sm cursor-default"
      onclick={onClose}
      transition:fade={{ duration: 150 }}
    ></button>

    <div
      class="relative z-10 w-full max-w-2xl rounded-3xl border border-white/15 bg-gradient-to-br from-gray-900/95 via-black/95 to-gray-900/95 backdrop-blur-3xl p-8 shadow-2xl {className}"
      transition:scale={{ duration: 200, easing: cubicOut, start: 0.96 }}
    >
      {#if title || description}
        <div class="mb-6 space-y-2">
          {#if title}
            <h2
              class="text-2xl font-bold leading-none tracking-tight bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent flex items-center gap-3"
            >
              {@render title()}
            </h2>
          {/if}
          {#if description}
            <p class="text-sm text-gray-400">{@render description()}</p>
          {/if}
        </div>
      {/if}
      {@render children()}
    </div>
  </div>
{/if}

// src/components/ui/dialog.tsx
import * as React from "react"
import { cn } from "@/lib/utils"

interface DialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  children: React.ReactNode
}

const Dialog: React.FC<DialogProps> = ({ open, onOpenChange, children }) => {
  if (!open) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center animate-in">
      <div
        className="fixed inset-0 bg-black/90 backdrop-blur-sm"
        onClick={() => onOpenChange(false)}
      />
      <div className="relative z-50 animate-in">
        {children}
      </div>
    </div>
  )
}

const DialogContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, children, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "relative w-full max-w-lg rounded-3xl border border-white/20 bg-gradient-to-br from-gray-900/95 via-black/95 to-gray-900/95 backdrop-blur-3xl p-8 shadow-2xl",
      className
    )}
    {...props}
  >
    {children}
  </div>
))
DialogContent.displayName = "DialogContent"

const DialogHeader = ({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) => (
  <div
    className={cn(
      "flex flex-col space-y-2 text-center sm:text-left mb-6",
      className
    )}
    {...props}
  />
)
DialogHeader.displayName = "DialogHeader"

const DialogTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h2
    ref={ref}
    className={cn(
      "text-2xl font-bold leading-none tracking-tight bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent",
      className
    )}
    {...props}
  />
))
DialogTitle.displayName = "DialogTitle"

const DialogDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn("text-sm text-gray-400", className)}
    {...props}
  />
))
DialogDescription.displayName = "DialogDescription"

export { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription }
