// src/lib/components/ui/Progress.svelte
<script lang="ts">
  import { cn } from "$lib/utils/cn";

  interface Props {
    value?: number;
    max?: number;
    class?: string;
    indeterminate?: boolean;
  }

  let {
    value = 0,
    max = 100,
    class: className = "",
    indeterminate = false,
  }: Props = $props();

  const percentage = $derived(Math.min(Math.max((value / max) * 100, 0), 100));
</script>

<div
  class={cn("relative h-2 w-full overflow-hidden rounded-full bg-white/5", className)}
  role="progressbar"
  aria-valuenow={value}
  aria-valuemin={0}
  aria-valuemax={max}
>
  {#if indeterminate}
    <div
      class="h-full w-1/3 rounded-full bg-gradient-to-r from-red-500 via-pink-500 to-red-500 absolute animate-[shimmer_1.5s_ease-in-out_infinite]"
      style="background-size: 200% 100%;"
    ></div>
  {:else}
    <div
      class="h-full rounded-full bg-gradient-to-r from-red-500 via-pink-500 to-red-500 transition-[width] duration-300 ease-out"
      style="width: {percentage}%; background-size: 200% 100%;"
    ></div>
  {/if}
</div>

// src/components/ui/progress.tsx
import * as React from "react"
import { cn } from "@/lib/utils"

interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value?: number
  max?: number
}

const Progress = React.forwardRef<HTMLDivElement, ProgressProps>(
  ({ className, value = 0, max = 100, ...props }, ref) => {
    const percentage = Math.min(Math.max((value / max) * 100, 0), 100)

    return (
      <div
        ref={ref}
        className={cn(
          "relative h-2 w-full overflow-hidden rounded-full bg-gray-800",
          className
        )}
        {...props}
      >
        <div
          className="h-full bg-gradient-to-r from-red-600 to-red-500 transition-all duration-300 ease-in-out"
          style={{ width: `${percentage}%` }}
        />
      </div>
    )
  }
)
Progress.displayName = "Progress"

export { Progress }
